language: R
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false
warnings_are_errors: false

jobs:
  include:
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_github("r-dbi/DBI")'
    - Rscript -e 'remotes::install_github("calejero/rswissknifedb")'
    #deploy:
    #  provider: script
    #  script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
    #  skip_cleanup: true

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
